### ISSUE TITLE
Error during npm installation

### ISSUE THREAD

**Issue by duzenko** [NickNaso/ghostscript4js#60]
I have installed the 32-bit version of GH 9.20 but the npm package fails to install, seemingly requiring the 64-bit files?

```

C:\dev\pss2-backend>npm i

> ghostscript4js@3.2.1 install C:\dev\pss2-backend\node_modules\ghostscript4js
> node-gyp rebuild


C:\dev\pss2-backend\node_modules\ghostscript4js>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Warning: Missing input files:
C:\gs\bin\gsdll64.dll        
C:\gs\bin\gsdll64.lib        
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\dev\pss2-backend\node_modules\ghostscript4js\build\Release\\nothing.lib
  Copying C:/gs/bin/gsdll64.dll to C:\dev\pss2-backend\node_modules\ghostscript4js/build/Release\gsdll64.dll
  The system cannot find the path specified.
  Copying C:/gs/bin/gsdll64.lib to C:\dev\pss2-backend\node_modules\ghostscript4js/build/Release\gsdll64.lib
  The system cannot find the path specified.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning M 
SB8064: Custom build for item "C:\gs\bin\gsdll64.dll" succeeded, but specified dependency "c:\gs\bin\gsdll64.dll" does not exist. Thi 
s may cause incremental build to work incorrectly. [C:\dev\pss2-backend\node_modules\ghostscript4js\build\ghostscript4js.vcxproj]     
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning M 
SB8065: Custom build for item "C:\gs\bin\gsdll64.dll" succeeded, but specified output "c:\dev\pss2-backend\node_modules\ghostscript4j 
s\build\release\gsdll64.dll" has not been created. This may cause incremental build to work incorrectly. [C:\dev\pss2-backend\node_mo 
dules\ghostscript4js\build\ghostscript4js.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning M 
SB8064: Custom build for item "C:\gs\bin\gsdll64.lib" succeeded, but specified dependency "c:\gs\bin\gsdll64.lib" does not exist. Thi 
s may cause incremental build to work incorrectly. [C:\dev\pss2-backend\node_modules\ghostscript4js\build\ghostscript4js.vcxproj]     
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning M 
SB8065: Custom build for item "C:\gs\bin\gsdll64.lib" succeeded, but specified output "c:\dev\pss2-backend\node_modules\ghostscript4j 
s\build\release\gsdll64.lib" has not been created. This may cause incremental build to work incorrectly. [C:\dev\pss2-backend\node_mo 
dules\ghostscript4js\build\ghostscript4js.vcxproj]
  ghostscript4js.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1104: cannot open file 'C:\dev\pss2-backend\node_modules\ghostscript4js\build\Release\gsdll64.lib' [C:\dev\pss2 
-backend\node_modules\ghostscript4js\build\ghostscript4js.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)        
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\pss2-backend\node_modules\ghostscript4js
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN pss2-backend@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ghostscript4js@3.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ghostscript4js@3.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\a\AppData\Roaming\npm-cache\_logs\2020-08-10T08_57_37_486Z-debug.log

C:\dev\pss2-backend>
```

**Comment by NickNaso** [comment]
This issue relates to https://github.com/NickNaso/ghostscript4js/issues/61

**Comment by NickNaso** [comment]
It's not enough change only `GS4JS_HOME` if you have the 32 bit version you need to change the env variables `GS4JS_LIB` and `GS4JS_DLL`.
